PREFIX ceon-product:  <http://w3id.org/CEON/ontology/product/>
PREFIX resourceODP:   <http://w3id.org/CEON/ontology/resourceODP/>
       
SELECT ?batch ?product_item ?bacth_volume                       
WHERE {    
    ?batch a resourceODP:BatchOfObjects ;
  		   ceon-product:batchOfProduct ?product_item ;
  		   resourceODP:batchSize ?bacth_volume .
 }  