PREFIX ceon-material:  <http://w3id.org/CEON/ontology/material/>
PREFIX dpp-info:       <http://w3id.org/dppo/ontology/dpp-info/>
PREFIX dpp-odp:        <http://w3id.org/dppo/ontology/dpp-odp/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX glass: <http://w3id.org/CEON/ontology/flatglass/>           
PREFIX qudt:  <http://qudt.org/schema/qudt/>      
PREFIX quantitykind: <https://qudt.org/vocab/quantitykind/>
PREFIX quantityunit: <http://qudt.org/vocab/unit/>
PREFIX ex:    <http://example.org/>            
       
SELECT ?window ?glass ?material ?contains                        
WHERE {    
    ?window  a glass:Window .      
    ?glass a glass:WindowGlass .
    ?dpp dpp-odp:describes ?window .            
    OPTIONAL {
        ?dpp dpp-info:containsInformation ?materialcharacteristic .
        ?materialcharacteristic dpp-info:isAbout ?glass ;
                            dpp-info:characteristic ?material ;
                            dpp-info:value ?contains .
        ?material a ceon-material:Material .
    }                                     
 }  